- name: Install nginx on all servers
  hosts: webservers

  tasks:
    - name: Install nginx on CentOS
      ansible.builtin.yum:
        name: nginx
        state: latest
        when: ansible_distribution == 'CentOS'

    - name: Install nginx on Debian/Ubuntu
      ansible.builtin.apt:
        name: nginx
        state: latest
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
    - name: Install nginx on RHEL/Fedora
      ansible.builtin.dnf:
        name: nginx
        state: latest
        when: ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat' 